apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: momoay003/backend:latest
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "199419992003"
            - name: DB_NAME
              value: "todoapp"
            - name: NODE_ENV
              value: "development"
            - name: JWT_SECRET
              value: "JS8LEGOAT"
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP